digit -> [0-9]
either[X,Y] -> $X | $Y
maybe2[X] -> $X | null
maybe4[X] -> maybe2[maybe2[$X]]
maybe8[X] -> maybe2[maybe4[$X]]

nounPrimitive ->
  maybe4["\\( (\\infty, 1) \\)-"] "category"
| "monoid"
| "monad"
| "presheaf"
| "sheaf"
| "endofunctor"
| "functor"
| "topos"
| maybe4["\\( (\\infty, 1) \\)-"] "topos"
| "image"
| "preimage"
| maybe4["\\( (\\infty, 1) \\)-"] "groupoid"
| "homology"
| "cohomology"
| "hom-object"
| "adjoint"
| "object"
| "bi-category"
| "bundle"
| "limit"
| "end"
| "cover"
| "hypercover"
| "embedding"
| maybe2["higher "] "homotopy"
| "pushout"
| "pullback"
| "product"
| "diagram"
| "morphism"
| "arrow"
| "complex"
| "resolution"
| "tensor"
| "adjunction"
| "unit"
| "isomorphism"
| "natural transformation"
| "chain complex"
| "spectrum"
| "operad"
| "extension"
| "structure"
| digit "-cell"
| "term"
| "type"
| either[either["sub-", null], null] "object classifier"

noun ->
  either[either["co-", null], null] nounPrimitive
| either[either[either["quasi-", null], null], null] nounPrimitive

nounPrimitives ->
  maybe4["\\( (\\infty, 1) \\)-"] "categories"
| "monoids"
| "monads"
| "presheaves"
| "sheaves"
| "endofunctors"
| "functors"
| maybe4["\\( (\\infty, 1) \\)-"] "topoi"
| "images"
| "preimages"
| maybe4["\\( (\\infty, 1) \\)-"] "groupoids"
| "homologies"
| "cohomologies"
| "hom-objects"
| "adjoints"
| "objects"
| "bi-categories"
| "bundles"
| "limits"
| "ends"
| "covers"
| "hypercovers"
| "embeddings"
| maybe2["higher"] "homotopies"
| "pushouts"
| "pullbacks"
| "products"
| "diagrams"
| "morphisms"
| "arrows"
| "resolutions"
| "tensors"
| "adjunctions"
| "units"
| "isomorphisms"
| "natural transformations"
| "chain complexes"
| "spectra"
| "operads"
| "extensions"
| "structures"
| digit "-cells"

nouns ->
  either[either["co-", null], null] nounPrimitives
| either[either[either["quasi-", null], null], null] nounPrimitives
