digit -> [0-9]
either[X,Y] -> $X | $Y

nounPrimitive ->
  "category"
| "monoid"
| "monad"
| "presheaf"
| "sheaf"
| "endofunctor"
| "functor"
| "topos"
| "image"
| "preimage"
| "groupoid"
| "homology"
| "cohomology"
| "hom-object"
| "adjoint"
| "object"
| "bi-category"
| "bundle"
| "limit"
| "end"
| "cover"
| "hypercover"
| "embedding"
| "homotopy"
| "pushout"
| "pullback"
| "product"
| "diagram"
| "morphism"
| "arrow"
| "complex"
| "resolution"
| "tensor"
| "adjunction"
| "unit"
| "isomorphism"
| "natural transformation"
| "chain complex"
| "spectrum"
| "operad"
| "extensions"
| "structure"
| digit "-cell"

noun ->
  either[either["co-", null], null] nounPrimitive
| either[either[either["quasi-", null], null], null] nounPrimitive

nounPrimitives ->
  "categories"
| "monoids"
| "monads"
| "presheaves"
| "sheaves"
| "endofunctors"
| "functors"
| "topoi"
| "images"
| "preimages"
| "groupoids"
| "homologies"
| "cohomologies"
| "hom-objects"
| "adjoints"
| "objects"
| "bi-categories"
| "bundles"
| "limits"
| "ends"
| "covers"
| "hypercovers"
| "embeddings"
| "homotopies"
| "pushout"
| "pullback"
| "products"
| "diagrams"
| "morphisms"
| "arrows"
| "resolution"
| "tensors"
| "adjunctions"
| "units"
| "isomorphisms"
| "natural transformations"
| "chain complexes"
| "spectra"
| "operads"
| "extensions"
| "structures"
| digit "-cells"

nouns ->
  either[either["co-", null], null] nounPrimitives
| either[either[either["quasi-", null], null], null] nounPrimitives
